### ISSUE TITLE
杂项, add useful resources

### ISSUE THREAD

**Issue by Voileexperiments** [24OI/OI-wiki#1024]
畢竟現在都9102了(,有很多大殺器嚴格不屬於OI某一特殊方面但可以增長各方面的姿勢和在各種場景下派上用場:

- [TIO.run](https://tio.run): 在線跑600+語言的代碼(大量esolang),茲磁各種類型的交互包括IO,超時60s(!),茲磁Wolfram Language(!!),簡單跑代碼
- [OEIS](https://oeis.org): 有整數序列不會就查OEIS吧,已經訓練成常識了(
- [ISC](http://wayback.cecm.sfu.ca/projects/ISC/ISCmain.html): 這個是實數反查表達式的,有時會用上場(?)
- [Compiler Explorer](https://godbolt.org/): 再也不怕不知道你的代碼被編譯成甚麼樣子了
- [Wolfram Alpha](https://www.wolframalpha.com): IO交互比較人性化的MMA(不,主要是用來求簡單導數/積分吧,當然也能做別的東西

TODO:
- 加入更多內容?
- 使用教程

**Comment by Voileexperiments** [comment]
等等發現原來有[简介 -> 	
OI Wiki 学习资源 -> 工具](https://oi-wiki.org/intro/resources/) orz

merge進去就好了(

**Comment by Xeonacid** [comment]
您开个pr？

**Comment by Ir1d** [comment]
:smile: 刚想说资源那页有一些内容了，如果要在杂项写一些使用教程/更detail的内容我觉得也蛮好的

**Comment by Voileexperiments** [comment]
#1027

**Comment by orzcyand1317** [comment]
这个 issue 是不是可以 close 了?

**Comment by Voileexperiments** [comment]
好了, closing
