### ISSUE TITLE
符號/變數/函數解釋不全

### ISSUE THREAD

**Issue by Voileexperiments** [24OI/OI-wiki#1028]
有些地方使用的符號/變數/函數沒有解釋,造成閱讀困難

---

例如[primes](https://github.com/24OI/OI-wiki/blob/master/docs/math/prime.md):

```
bool millerRabin(int n) {
  if (n < 3) return n == 2;
  for (int i = 1; i <= s; ++i) {
    int a = rand() % (n - 2) + 2;
    if (quickPow(a, n - 1, n) != 1) return 0;
  }
  return 1;
}
```

`i <= s`裡`s`的意思沒解釋過(其實是檢驗次數)

同理,`quickPow`定義在前一章[快速幂](https://github.com/24OI/OI-wiki/blob/master/docs/math/quick-pow.md),建議在代碼塊用comment標註

---

[https://github.com/24OI/OI-wiki/blob/master/docs/string/ac-automaton.md](AC自動機):

> 共有 $m$ 个状态，第 $i$ 个状态表示已经匹配了前 $i$ 个字符
> $$ trans[i][x] = \begin{cases} i + 1, & \text{if $b[i] = x$} \[2ex] trans[next[i]][x], & \text{else} \end{cases} $$
>（约定 $next[0]=0$ ）

`b`, `trans`, `next`是啥鬼來著?

---

其他地方沒仔細看,估計抓起來的話還有一把所以開個issue了,不過定義符號是很重要的 ^_^

**Comment by orzcyand1317** [comment]
thx!
我来 fix 一下

**Comment by orzcyand1317** [comment]
以及我觉得 quickPow 的没必要修改吧...quickPow 本身已经是「快速幂」的意思了
如果 quickPow 也需要修改的话那是不是每个页面都需要把所有前置知识都写一遍?

**Comment by Voileexperiments** [comment]
> 以及我觉得 quickPow 的没必要修改吧...quickPow 本身已经是「快速幂」的意思了
> 如果 quickPow 也需要修改的话那是不是每个页面都需要把所有前置知识都写一遍?

我覺得會有兩個問題:

1. wiki的閱讀習慣不是由頭到尾順序閱讀的,不能依賴讀者已經看過以前部份,而且素數和快速幂也沒有關係嘛(
我倒覺得下個comment或留個鏈結提一下快速幂的章節就好
2. 代碼塊的一般使用場景是直接把代碼複製黏貼跑的,所以自舉能力很重要,有依賴就很不方便了,要把剩下的部份補完

**Comment by orzcyand1317** [comment]
有道理...其实我一直觉得应该加个 Reference 或者「前置知识」的...
