### ISSUE TITLE
【关于北京大学算法协会】

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#1034]
Hi，大家好！

不知道诸位有没有注意到去年十二月成立的北京大学算法协会（pkusaa）呢？

是这样的，他们那边希望能参与进来，一起建设 Wiki 这个项目，开这个 issue 呢，是想征求一下大家的意见（

可能对我们带来的影响：
1. pkusaa 的大佬们想要参与到页面内容的建设（（希望可以对 wiki 内页面质量带来质的飞跃
2. 协会投入资金到 wiki 这边（保证 wiki 的可持续发展），可能需要在合适的位置标注一下赞助信息

可能比较突然，然后欢迎大家把相关的 想法/建议/意见 在周四（3.7）中午 12:00 前 comment 在这个 issue 下面或者私聊我，谢谢！

感谢大家的关注和支持，希望 wiki 越办越好！

ir1d
2019.3.5

**Comment by Tiger3018** [comment]
会不会改名为算法wiki（逃

**Comment by Chrogeek** [comment]
OI-wiki β
&nbsp;&nbsp;&nbsp;&nbsp;Sponsored by PKUSAA
（逃

**Comment by abc1763613206** [comment]
只要遵循正常贡献步骤，内容方面应该没啥问题吧？   
（而且我觉得还可以加一个`本内容由北京大学 XXX 编写/审定`，有名校背书吸引力应该好点）    
赞助的话个人认为首页加个链接或者logo就行了，类似于sponsor那种    
（说不定哪天蹦出来个wiki.saa.pku.edu.cn教育网IPv6镜像呢233）

**Comment by StudyingFather** [comment]
pku加入oi-wiki的维护的话，当然是资瓷的（毕竟dalao的加入对wiki质量的提升肯定是非常有帮助的

赞助信息的话，在首页加个赞助标识就好了吧（

**Comment by BalanceUhen** [comment]
这是好事吧?

**Comment by yizr-cnyali** [comment]
> 只要遵循正常贡献步骤，内容方面应该没啥问题吧？
> （而且我觉得还可以加一个`本内容由北京大学 XXX 编写/审定`，有名校背书吸引力应该好点）
> 赞助的话个人认为首页加个链接或者logo就行了，类似于sponsor那种
> （说不定哪天蹦出来个wiki.saa.pku.edu.cn教育网IPv6镜像呢233）

要不试试邀请thu也加进来

**Comment by yizr-cnyali** [comment]
pku加入**OI-Wiki**维护挺棒的啊~~说不定还可以吸引thu也加进来~~
至于赞助信息嘛……
显然可以在首页加个赞助标识
要不建个pkusaa的github组织然后加到**OI Wiki** Team的合照里面?

**Comment by Chrogeek** [comment]
> pku加入OI-Wiki维护挺棒的啊说不定还可以吸引thu也加进来
> 至于赞助信息嘛……
> 显然可以在首页加个赞助标识
> 要不建个pkusaa的github组织然后加到OI Wiki Team的合照里面?

手动 @kawa-yoiko @Pisces000221

**Comment by kawa-yoiko** [comment]
突然被 cue 不知所措

**Comment by Chrogeek** [comment]
> 突然被 cue 不知所措

「说不定还可以吸引thu也加进来」
其实是想问问你@kawa-yoiko 有没有酒井算协的联系方式233

**Comment by kawa-yoiko** [comment]
行…… 窝或许可以问问 THUSAAC 有没有兴趣……

**Comment by partychicken** [comment]
滋磁

**Comment by Allen-Yuk-Tak-Lee** [comment]
我觉得是好事
只要oiwiki不商业化，对于有大佬加入，我投赞成票。

**Comment by HeRaNO** [comment]
窝觉得可以，至少可以持续发展下去了（
