### ISSUE TITLE
seo优化后 主页特殊标签失效

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#1058]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

主页特殊标签失效，gitalk没有被禁用

- 你是否正在着手修复？

在校修不了 cue一下@Ir1d 和   @Himself65      吧

- 如何复现？

首页底部

issue 标题请写为 要汇报的主要内容

**Comment by abc1763613206** [comment]
@Ir1d 看样子要跳过index文件？

**Comment by Himself65** [comment]
@abc1763613206 自己加ignore files

**Comment by Himself65** [comment]
https://github.com/24OI/OI-wiki/blob/31f0bdc9d41a7d999a1b4c9922aaa75848c60357/scripts/add-description.js#L20-L22

```js
const ignoreFiles = [
  /^index/
]
...
   if (ignoreFIles.some(regex => regex.test(file))) {
     return
   }
```

**Comment by Ir1d** [comment]
我觉得应该在脚本里判断一下如果md文件本身有meta就不要插入分隔符？
维护这个 ignoreFiles 会很费劲吧

**Comment by Himself65** [comment]
应该可以搞到在build之前处理这些preload脚本，而而且不会影响到源文件，但是我不掌握`python`（~~垃圾python~~）就懒得研究了

**Comment by abc1763613206** [comment]
所以这个问题先放一下？

**Comment by abc1763613206** [comment]
```
const fs = require("fs")
const lines = fs.readFileSync("FILENAME.TXT").toString().split("\n") 
if (lines.includes(":disqus")) { // Do something. } 

```

找到个差不多的方案？    
然后给meta判断分隔符

**Comment by abc1763613206** [comment]
暂时没有可行的方案            
因此先咕掉
