### ISSUE TITLE
Iteration Plan for Spring 2019

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#1065]
1. 统计一下低质量版面

目前想到的：缺少例题也算

2. 整理近期想开的新坑 list

#936 #148

**Comment by GodCowC** [comment]
线性规划的页面讲的太浅了吧233

**Comment by MrRobertYuan** [comment]
高精度板块或许可以考虑加一个压位实现的高精度~

**Comment by Akanesasu** [comment]
初等数论函数相关的比较少 或者页面比较散？

**Comment by partychicken** [comment]
> 初等数论函数相关的比较少 或者页面比较散？

内容还算比较全吧。。。
分类方式的话，并不知道应该怎么改

**Comment by partychicken** [comment]
迭代加深缺少例题

提供一些：埃及分数，[SCOI2005]骑士精神

**Comment by partychicken** [comment]
AC自动机缺少例题及fail树相关内容

**Comment by Saigyouji** [comment]
内容缺失的页面:
置换群，数值积分，原根，KdTree，Euler Tour Tree，k短路，旋转卡壳（估计还有很多其他页面）空的
没有可并堆
我好像也没看到树剖……？（是不是眼瞎了

可以再完善的页面:
最小生成树那里还有个Bxxx的算法，记得有的地方讨论过这几个算法的不错的例题我去问问
Treap那里证明没补，以及还有用finger search做nlog n合并的部分(我记得是不是dwj的集训队论文写了)
可持久化平衡树那里我记得之前看到过几个关于记父亲问题的讨论
FWT那里vfk的集训队论文里有更深入的讨论
概率和期望那里讨论的还是有点少，本来是个挺大的topic
博弈论那里还有挺多内容的
平面图那个Topic也挺大的…而且可能感觉可能会涉及点计算几何内容
虚树感觉移到图论里比较好

其他建议：
统一代码风格和语言(咋还有pascal代码的)
改善图片质量以及增加图片说明(推广点作图工具和方法…？)
先把高频率考点的内容质量再提高点…？放点例题啥的（至少放个题号list也行），毕竟有些东西大家退役了也没用过

**Comment by WAAutoMaton** [comment]
@Saigyouji 可并堆是有的，“配对堆”条目就是，不过常用的左偏树确实没有。

**Comment by wavwing** [comment]
https://oi-wiki.org/string/sam/
别看这个翻译的很全，但是它的语序颠倒以及硬翻很多。。。很容易误导初学者。

**Comment by yizr-cnyali** [comment]
> 线性规划的页面讲的太浅了吧233

喵w 我只会搞图解法,更完善的内容你们补充吧
QAQ

**Comment by abc1763613206** [comment]
我希望能把PR的六个锅补掉233

**Comment by yizr-cnyali** [comment]
数据结构部分希望能增加对zkw线段树的介绍

**Comment by abc1763613206** [comment]
> https://oi-wiki.org/string/sam/
> 别看这个翻译的很全，但是它的语序颠倒以及硬翻很多。。。很容易误导初学者。
> 
> > <img alt="" width="48" src="../../favicon.ico">**[后缀自动机 (SAM) - OI WikinO(n)O(n)kO(n\log k)sst_0t_0t_0sst_0st_0sst_0t_0s=``"s=``a\!"s=``aa\!"s=``ab\!"s=``abb\!"s=``abbb\!"endposstendpos(t)st``abcbc\!"endpos(``bc\!")=2,\,4t_1t_2endposendpos(t_1)=endpos(t_2)sendposendposendpos+1endposuwsuwlength(u)\le length(w)endposuwendposuwswuwsendposuwlength(u)\le length(w)endposendpos(w)endpos(u)uw\begin{cases} endpos(w)\subseteq endpos(u)&\text{若 $u$ 为 $w$ 的一个后缀}\\ endpos(w)\cap endpos(u)=\emptyset&\text{另一种情况}\\ \end{cases}endpos(u)endpos(w)uwuwwuendpos(w)endpos(u)endpos[x,\,y]endpos1endposwuuw[length(u),\,length(w)]wswuswwendposlinkv\ne t_0vendposwwwttlink(v)wendpost_0endpos(t)=\{-1,\,0,\,\ldots,\,length(s)-1\}t_0v\ne t_0link(v)t_0endposendposv\ne t_0link(v)endpos(v)\subseteq endpos(link(v))endpos``abcbc\!"sendpost_0endposvlongest(v)len(v)shortest(v)minlen(v)longest(v)[minlength(v),\,len(v)]v\ne t_0longest(u)minlen(v)-1t_0endposv\ne t_0link(v)minlen(v)minlen(v)=len(link(v))+1.v_0t_0[minlen(v_i),\,len(v_i)][0,\,len(v_0)]lenlinkt_001,\,2,\,\ldotslen=0link=-1-1clastclast=0lastcurlen(cur)len(last)+1link(cur)lastccurcpp-1link(cur)0pcqlen(p) + 1 = len(q)len(p)+1=len(q)link(cur)qqcloneqlenlen(clone)len(p)+1curcloneqclonepcqclonelastcurslastss(p,\,q)len(p)+1=len(q)len(p)+1len(p)+1q(p,\,q)len(q)=len(p)+1curqlen(q)>len(p)+1qlen(p)+1s+csqlen(p)+1qclonelen(clone)len(p)+1qqclonecloneqqclonecurcloneqclonew+cwpp-1qkO(n\log k)O(n)kO(n)O(nk)O(1)lastcqcloneqcloneqclonev=longest(p)ssvlastk(k\ge2)v+ccurlastlongest(link(link(last))nO(n)O(n\log k)O(nk)kO(n)kkns2n-1n\ge2n-22endposendposn2n-1n``abbb\ldots bbb\!"2n-1ns3n-4n\ge 3t_02n-2(p,\,q)cu+c+wupwpu+c+wuwu+c+wssnu+c+wsn-13n-3``abbb\ldots bbb\!"3n-33n-4``abbb\ldots bbbc\!"kTPPTO(length(T))TPTt_0PPTPTPO(length(P))PSSSt_0d[v]vd[v]=1+\sum_{w:(v,\,w,\,c)\in DAWG}d[w]d[v]vd[t_0]-1O(length(S))Sd[v]ans[v]d[v]ans[v]ans[v]=\sum_{w:(v,\,w,\,c)\in DAWG}d[w]+ans[w]wd[w]vO(length(S))kSK_ikkkkO(length(S))O(length(ans)\cdot k)anskSS+SSlength(S)O(length(S))TPPTTvendpos(v)cnt[v]vTendposendposcntt_0cnt=1lencnt[v]cnt[link(v)]+=cnt[v]length(T)iicnt1cnt0vcnt[link(v)]+=cnt[v]vcnt[v]cnt[v]O(length(T))cntcnt[t]t0O(length(P))TPTPfirstposvfirstpos[v]endposendposfirstposcurfirstpos(cur)=len(cur)-1qclonefirstpos(clone)=firstpos(q)firstpos(cur)firstpos(t)-length(P)+1tPO(length(P))TTfirstpostTfirstpos(t)PPttfirstposO(answer(P))endposfirstposSSSd[v]vvd[v]d[v]=1d[v]=1+\min_{w(v,\,w,\,c)\in SA}d[w]d[t_0]d[]STSTXSTSTSTvlv=t_0l=0T[i]vT[i]lv=link(v)llen(v)l-1T[i]Sv=l=0lO(length(T))llkS_iXTD_iT=S_1+D_1+S_2+D_2+\cdots+S_k+D_k.TS_iS_jD_jD_1,\,\ldots,\,D_{j-1},\,D_{j+1},\,\ldots,\,D_kD_ivlongest(v)](https://oi-wiki.org/string/sam/)**OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛

fixed on #1065

**Comment by guanwening** [comment]
diff --git a/Gemfile.lock b/Gemfile.lock
index 0d9d5d466..e15397c53 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -195,7 +195,7 @@ GEM
       jekyll-seo-tag (~> 2.0)
     jekyll-titles-from-headings (0.5.1)
       jekyll (~> 3.3)
-    jekyll-watch (2.2.0)
+    jekyll-watch (2.2.1)
       listen (~> 3.0)
     jemoji (0.10.2)
       gemoji (~> 3.0)
@@ -217,7 +217,7 @@ GEM
     multipart-post (2.0.0)
     nokogiri (1.10.1)
       mini_portile2 (~> 2.4.0)
-    octokit (4.13.0)
+    octokit (4.14.0)
       sawyer (~> 0.8.0, >= 0.5.3)
     parallel (1.14.0)
     pathutil (0.16.2)

**Comment by guanwening** [comment]
https://github.com/24OI/OI-wiki/issues/1065#issuecomment-478208776

**Comment by ranwen** [comment]
1. 复数部分缺少对单位根的介绍 但FFT部分和原根部分均直接使用了这个词
2. 基础部分->递归&分治 最后一道例题中 "统计左右两侧贡献"中使用了双指针 但此文及全wiki未具体描述(对应长期计划大概为 完善细小知识点？)
3. 建议根据难度和常用度 将 "排序" 词条重新排序
4. 字符串->标准库 里面 怎么有几个函数鸽掉了啊
5. 数学->分块打表 这个内容放到数学分类是不是有点不够合适
6. 数据结构里面 可以把线段树放到BIT前面 以及可以增加 区间修改区间查询的特(wu)殊(yong)技巧

快速浏览了一下 抽空再仔细研究词条

**Comment by partychicken** [comment]
> 1. 复数部分缺少对单位根的介绍 但FFT部分和原根部分均直接使用了这个词
> 2. 基础部分->递归&分治 最后一道例题中 "统计左右两侧贡献"中使用了双指针 但此文及全wiki未具体描述(对应长期计划大概为 完善细小知识点？)
> 3. 建议根据难度和常用度 将 "排序" 词条重新排序
> 4. 字符串->标准库 里面 怎么有几个函数鸽掉了啊
> 5. 数学->分块打表 这个内容放到数学分类是不是有点不够合适
> 6. 数据结构里面 可以把线段树放到BIT前面 以及可以增加 区间修改区间查询的特(wu)殊(yong)技巧
> 
> 快速浏览了一下 抽空再仔细研究词条

FFT中介绍单位根了吧，您再仔细看看？

**Comment by ranwen** [comment]
> > 1. 复数部分缺少对单位根的介绍 但FFT部分和原根部分均直接使用了这个词
> > 2. 基础部分->递归&分治 最后一道例题中 "统计左右两侧贡献"中使用了双指针 但此文及全wiki未具体描述(对应长期计划大概为 完善细小知识点？)
> > 3. 建议根据难度和常用度 将 "排序" 词条重新排序
> > 4. 字符串->标准库 里面 怎么有几个函数鸽掉了啊
> > 5. 数学->分块打表 这个内容放到数学分类是不是有点不够合适
> > 6. 数据结构里面 可以把线段树放到BIT前面 以及可以增加 区间修改区间查询的特(wu)殊(yong)技巧
> > 
> > 快速浏览了一下 抽空再仔细研究词条
> 
> FFT中介绍单位根了吧，您再仔细看看？

抱歉之前没看到(不过我建议把这部分知识移到 复数部分)

以及中间"单位复根的引入"有个公式有点问题(指缺括号)

**Comment by abc1763613206** [comment]
新的计划已经增修完毕，goto #1212
