### ISSUE TITLE
关于在 Gitalk 评论里直接提交 bug 的建议

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#1067]
主要是感觉目前的建议散布在评论里，很少有人来直接提issue指正。       

所以想直接建一个集合的issue，然后修改底部，引导提建议时直接reference到那个issue     

大概是在发现错误那一行后面加上按钮，然后直接修改gitalk的框来让读者输入内容    

真要实现的话个人觉得没什么难度，比如我已经在FAQ里面reference到了1065，亲测可用

**Comment by Tiger3018** [comment]
应该是指的内容错误？

可能需要码一点，但是可以先考虑在gittalk那里加一个“作为显示/内容错误提交”的按钮或复选框。

**Comment by partychicken** [comment]
我觉得可能需要简化提issue的过程，引导和要求也明确一些。如果提issue和开pr一样方便的话就好很多

**Comment by Ir1d** [comment]
可以用这种 `https://github.com/24OI/OI-wiki/issues/new?title=foo&body=bar`，也是一键，不知道是不是像 @partychicken 说的和 pr 一样方便
