### ISSUE TITLE
bug: 搜索栏加载数据方式错误

### ISSUE THREAD

**Issue by Himself65** [24OI/OI-wiki#1071]
搜索栏数据加载影响了主线程，需要改成异步加载数据

https://github.com/Ir1d/mkdocs-material/blob/0d30980dc856236c844e9d6143e14425c2b61724/src/assets/javascripts/components/Material/Search/Result.jsx#L127

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)

- [x] 你是否正在着手修复？

**Comment by Himself65** [comment]
I think this bug has fixed currently

**Comment by Ir1d** [comment]
虽然不知道发生了啥.. thx anyway
