### ISSUE TITLE
DP优化要不要细分成优化状态和优化转移？

### ISSUE THREAD

**Issue by partychicken** [24OI/OI-wiki#1078]
感觉dp不止有斜率优化之类优化转移过程的优化，还有优化状态设计的题吧。。

至少先把坑开出来

**Comment by orzcyand1317** [comment]
这都是 DP 优化啊...
为什么不在同一个页面里放两个 title 呢？）

**Comment by partychicken** [comment]
这么搞页面太长了吧

**Comment by partychicken** [comment]
我甚至觉得DP优化应该拆成类似数学里同余相关那种样式

**Comment by orzcyand1317** [comment]
那我开个 pr 改成 optimization/state_optimization.md 和 optimization/trans_optimization.md？（

**Comment by partychicken** [comment]
可以讨论一下吧，我觉得

**Comment by partychicken** [comment]
我觉得把斜率优化，单调队列优化，四边形不等式这些都拆成子目录比较好

**Comment by orzcyand1317** [comment]
ir1d 鸽鸽发话了！我来拆
（那就 close 了
