### ISSUE TITLE
add 单纯形

### ISSUE THREAD

**Issue by huhaoo** [24OI/OI-wiki#1091]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
单纯形

- 英文叫什么？
Simplex

- 有什么参考资料？
http://www.cnblogs.com/ECJTUACM-873284962/p/7097864.html （至今看到写得最好的blog）

issue 标题请写为 'add ' + 要添加的内容

**Comment by AngelKitty** [comment]
> @AngelKitty Hi，大佬有兴趣投稿过来吗

我正准备睡觉来着，一个issue把我叫醒2333，行啊，要不下周我整理一下吧，下周一周三期末考，考完就舒服了

**Comment by Ir1d** [comment]
@AngelKitty dbq.. 打扰了.. 期末顺利～

**Comment by AngelKitty** [comment]
> @AngelKitty dbq.. 打扰了.. 期末顺利～

你们啥时候放假吖qwq
