### ISSUE TITLE
未开启评论所需的 issue

### ISSUE THREAD

**Issue by ChungZH** [24OI/OI-wiki#1094]
- [珂朵莉树](https://oi-wiki.org/misc/odt/) 
- [计算理论基础](https://oi-wiki.org/misc/cc-basic/)
- [悬线法](https://oi-wiki.org/misc/largest-matrix/)
- [平面最近点对](https://oi-wiki.org/geometry/nearest-points/) 
- [图论杂项](https://oi-wiki.org/graph/misc/)
- [平面图](https://oi-wiki.org/graph/planar/)
- [哈密顿图](https://oi-wiki.org/graph/hamilton/)
- [最小树形图](https://oi-wiki.org/graph/mdst/)
- [DFS 序](https://oi-wiki.org/graph/dfs-order/) 

~~好累啊......~~ 
@Ir1d 来看看吧！

**Comment by abc1763613206** [comment]
这里要不当评论相关锅集合？   
（我可以改下模板指向这里）

**Comment by Ir1d** [comment]
啊 啥叫模板指向这里

**Comment by abc1763613206** [comment]
> 啊 啥叫模板指向这里

未找到相关的 Issues 进行评论   
请至24OI/OI-wiki#1094进行反馈

**Comment by Ir1d** [comment]
哦哦。。。我觉得具体问题新开issue其实也没啥 :joy: 你这么说指过来当然也 ok 啦～

过几天有空的时候我来解决一下这个 issue…… 最近在 rush ddl

**Comment by Ir1d** [comment]
thx! 应该是都开了～
