### ISSUE TITLE
add mex

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#110]
以及不太清楚这东西放哪……

**Comment by P6174** [comment]
放博弈论那里呗
mex 最早好像就是在 Nim 游戏中提出来的？

**Comment by P6174** [comment]
另外，我觉得不用单独给 mex 开一个页面

**Comment by Xeonacid** [comment]
@P6174 那样的话线段树/莫队+分块毫无游戏体验（
mex也是一道题啊hhhh

**Comment by Alpha1022** [comment]
这个……  
在博弈论那里放叭，  
然后数据结构维护在相应的页面添加此内容叭。

**Comment by i-Yirannn** [comment]
咕了太久就关掉了

**Comment by Ir1d** [comment]
看错了🌚 已经加过了
