### ISSUE TITLE
OI Wiki Meetup

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#1107]
大家好！

这周五我们借了个教室，感兴趣的同学可以来聊聊天，大概内容可能是讨论接下来的计划～

时间：2019 年 3 月 29 日 20:40
地点：北京大学四教 505

**Comment by TrisolarisHD** [comment]
有没有全国各地分会场啊 / 大雾

**Comment by partychicken** [comment]
有没有远程连线啊？

**Comment by interestingLSY** [comment]
有没有全国各地分会场啊

**Comment by yizr-cnyali** [comment]
> 有没有远程连线啊？
+1

**Comment by Ir1d** [comment]
没有.. 期待一下 APIO 约饭吧 :joy:

**Comment by TrisolarisHD** [comment]
> 没有.. 期待一下 APIO 约饭吧 😂

烤大猪蹄子! / 大雾

**Comment by yizr-cnyali** [comment]
> 没有.. 期待一下 APIO 约饭吧

~~显然~~我不会去今年的APIO啊。。。
那我还是等明年吧。。

**Comment by abc1763613206** [comment]
在学校很无奈啊，希望有录播😂    
另：来bj旁边的sd看看啊（

**Comment by Ir1d** [comment]
![image](https://user-images.githubusercontent.com/10709657/55240129-1cd5c880-5273-11e9-9a3f-0b62b8088879.png)
预计 3 人，实到 11 人，超额完成任务（
