### ISSUE TITLE
jsdelivr 出锅导致站点无法渲染

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#1177]
如题。          

由于jsdelivr的SSL证书到期且开启了HSTS，目前全站均无法渲染。                 
相关 Issues ：           
  -  https://github.com/jsdelivr/jsdelivr/issues/18145
  -  https://github.com/jsdelivr/jsdelivr/issues/18146
  -  https://github.com/jsdelivr/jsdelivr/issues/18147

目前我们正在模板方面紧急更换 CDN ，预计故障修复后换回，敬请谅解。

**Comment by abc1763613206** [comment]
目前已经对 CDN 进行了 hotfix ，站点暂时恢复渲染。      
我们将持续关注 jsdelivr 状况。

**Comment by wangzhilongh** [comment]
现在已经修复了吗？
为啥我这里还是不能正常访问cdn资源？

**Comment by wangzhilongh** [comment]
谢谢！

**Comment by yoyo837** [comment]
考虑下unpkg

**Comment by abc1763613206** [comment]
> @yoyo837 考虑下unpkg


see #1178

**Comment by abc1763613206** [comment]
jsdelivr 方面的 SSL 证书问题现已修复         
https://github.com/jsdelivr/jsdelivr/issues/18145#issuecomment-485067092
