### ISSUE TITLE
我是递归&分治的主要贡献者，请问为什么偏偏没有我的名字？

### ISSUE THREAD

**Issue by fudonglai** [24OI/OI-wiki#1191]
https://coding.oi-wiki.org/basic/divide-and-conquer/

整篇文章都是我投递的，但作者偏偏没有我的名字，这是为什么？
我知道这是基本内容，但是请重视作者的劳动成果！

**Comment by fudonglai** [comment]
![image](https://user-images.githubusercontent.com/37220920/56707379-26a3fc00-674b-11e9-8eb2-254cce882e07.png)

**Comment by WAAutoMaton** [comment]
贡献者部分是从 git 的 commit 记录中自动生成的，而你的 commit 是匿名的，所以无法从中读取贡献者，并不是故意不写上去。
![image](https://user-images.githubusercontent.com/24771667/56708203-68827180-674e-11e9-88c3-a204a4f829c2.png)

**Comment by ranwen** [comment]
感谢您关注此问题

文章文末的作者是根据git的日志自动生成的

经过我的查询 您对此页面的贡献应为 #1145
commit为
2fbefad45680d12e79780df59cb398481b68484b
29b3a5542b2ec9807cc83c78253e8ff783b62d77

但是在这两个commit内 可能由于您本地git设置有误（使用了匿名用户 并且在本地git使用了错误的邮箱与用户名 可以参考 https://www.v2ex.com/t/557641 ）而导致commit无法正确显示您的用户名

在git日志内 您的用户名为"Your Name" 邮箱为"you@example.com"
也就说 文末的"invalid-email-address"是自动获取的您的username
建议您下次在提交的时候使用 git log  检查用户名和邮箱是否正确 避免后续修改所造成的困扰
我们会处理尽快这个问题 请您谅解

**Comment by Ir1d** [comment]
归入 #480 的问题，期待 #480 能尽快解决吧

**Comment by Enter-tainer** [comment]
#2358，已经手动添加
