### ISSUE TITLE
maybe we need a favicon?

### ISSUE THREAD

**Issue by cjsoft** [24OI/OI-wiki#120]
maybe we need a favicon?

**Comment by Ir1d** [comment]
有一个更好？之前没想好用什么，现在用的是font-awesome的图标好像，应该是在mkdocs.yml里配的

**Comment by Ir1d** [comment]
@MingqiHuang https://material.io/tools/icons/?icon=school&style=baseline

**Comment by MingqiHuang** [comment]
#331 resolved this. Further discussion is welcome.
