### ISSUE TITLE
可持久化线段树 格式渲染问题

### ISSUE THREAD

**Issue by StudyingFather** [24OI/OI-wiki#1235]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

在 [可持久化线段树](https://oi-wiki.org/ds/persistent-seg/) 页面最下面的删除线内容被错误渲染成了`<sub></sub>`的格式（显示效果为字体变小了）。

- 你是否正在着手修复？

还没有 QAQ

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by abc1763613206** [comment]
看样子那一段warning也没有渲染......

**Comment by Ir1d** [comment]
https://daringfireball.net/projects/markdown/syntax 这里不支持吧

**Comment by Ir1d** [comment]
可以算进 mkdocs 的问题，但是另一方面不知道 wiki 里为什么必须要使用删除线..? 🤔

**Comment by TrisolarisHD** [comment]
@Ir1d 因为他们想皮🤔

**Comment by abc1763613206** [comment]
大概那段主观化的语句可以修正一下？

**Comment by abc1763613206** [comment]
fixed in https://github.com/24OI/OI-wiki/commit/88cef54b349b64abaf40abda99c0e935d8e17a12
