### ISSUE TITLE
更新卡特兰数的几个公式

### ISSUE THREAD

**Issue by kenlig** [24OI/OI-wiki#1261]
递推：h(0) = h(1) = 1 ; h(n) = h(0) * h(n-1) + h(1) * h(n-2) + ... + h(n-1) * h(0)  其中 n>=2
递推2：h(n) = h(n-1) * (4*n-2) / (n+1)
组合数1：已经写了
组合数2：h(n) = c(2n,n) - c(2n,n-1)

**Comment by Ir1d** [comment]
closed in #1262
