### ISSUE TITLE
add 析合树

### ISSUE THREAD

**Issue by sshwy** [24OI/OI-wiki#1296]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

**析合树**

- 英文叫什么？

**Divide-combine Tree**

（LCA的PPT上所写的是 A Simple Data Structure for Consecutive Sub-segments，但我自己口糊了一个更加贴切的英文名字～）

- 有什么参考资料？

**《简单的连续段数据结构 - A Simple Data Structure for Consecutive Sub-segments》 WC2019营员交流**

issue 标题请写为 'add ' + 要添加的内容

**Comment by sshwy** [comment]
另外文章我已经准备好了，希望尽快受理

**Comment by Ir1d** [comment]
0.0 受理是指..? @sshwy

**Comment by sshwy** [comment]
开个wiki的页面让我放文章上去QAQ

**Comment by Ir1d** [comment]
https://github.com/24OI/OI-wiki/blob/master/docs/ds/divide-combine.md 放在这里啦～

其实开页面也是通过开 pr，只不过网页上貌似不是很方便..

**Comment by Xeonacid** [comment]
@Ir1d 现在挺方便了，直接Create new file

**Comment by Ir1d** [comment]
@Xeonacid 赞
