### ISSUE TITLE
suggest : Use squash merge and amend commit in certain condition 

### ISSUE THREAD

**Issue by Xeonacid** [24OI/OI-wiki#130]
如果几个 commit 都是在做同一件事，或者说后面的 commit 是对前面的小修补，我们可以在 commit 时使用`git commit --amend`，或在 merge 时使用 squash merge，将几个 commit 合成一个，这样可以使 master 分支保持整洁。
![snipaste_2018-08-19_11-17-46](https://user-images.githubusercontent.com/13995937/44305078-8e769b80-a3a1-11e8-8dc9-e229a4452873.png)
（如果不是同一件事就别合并了23333

Example: #93 #122 #127 

如何？

**Comment by Ir1d** [comment]
滋兹。:+1: 
其实都行（最开始一直在 squash ，后来感觉没啥大区别

**Comment by Ir1d** [comment]
建议以后一个 pr 只做一件事，这样 squash 之后不会把几个内容合到一个 commit 里面= =

以及为了防止（我）日后点错，已经关了 `create a merge commit`，默认是 squash……
