### ISSUE TITLE
add Lucas&exLucas theorem

### ISSUE THREAD

**Issue by 1170300206** [24OI/OI-wiki#1309]
### I think it's more ideal to add some concepts about Lucas&exLucas theorem.
- 希望添加的是什么？
What would you like to add?
卢卡斯定理&拓展卢卡斯定理

- 英文叫什么？
what's its English name?
Lucas&exLucas theorem

- 有什么参考资料？
Is there any reference?
No reference

**Comment by abc1763613206** [comment]
duplicate. see #1255
