### ISSUE TITLE
建议：不止例题，也给出一些练习题

### ISSUE THREAD

**Issue by hsfzLZH1** [24OI/OI-wiki#205]
建议在每个算法专题之后给出一些练习题，只有例题可能是不够的qwq

**Comment by Ir1d** [comment]
练习题和例题的区别是……？

**Comment by LuoshuiTianyi** [comment]
例题会有详细的讲解而习题是自主练手的......吧

**Comment by AndrewWayne** [comment]
OI-Wiki主要还是百科性质题目有点冗余吧……

**Comment by Ir1d** [comment]
参考：比如 algowiki, geeksforgeeks 再比如 wcipeg.com algo.is 都是配了题目的

**Comment by Chen-Py** [comment]
在每个算法后头加上练习板块然后搞几个链接传送到OJ去~怎么样
