### ISSUE TITLE
Add std :: vector and Add std :: priority_queue 我在写

### ISSUE THREAD

**Issue by i-Yirannn** [24OI/OI-wiki#238]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

- 英文叫什么？

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by Ir1d** [comment]
Landed in #299 #254
