### ISSUE TITLE
Should magic be removed/modified?

### ISSUE THREAD

**Issue by Xeonacid** [24OI/OI-wiki#26]
#23 added [magic.md](https://github.com/24OI/OI-wiki/blob/master/docs/introduction/magic.md), which has little to do with OI, as an algorithm contest.

As we all know, its contents violate the law of PRC, making this project unsuitable to be spreaded publicly.

So I think we'd better remove it, or modify it. What do you all think?

**Comment by Ir1d** [comment]
Acctually I don't think it's against the law of PRC, and notice that OI-Wiki is actually different from algorithm-wiki.
Anyway, i'll leave this issue open for a while for open discussion. Feel free to share your ideas.
BTW, I think it's a good idea to move it off the front page and re-order the contents.

**Comment by Xeonacid** [comment]
@Ir1d Many items refer to bypass the GFW without permitted or viewing illegal website. 🌚   

Move it off the front page LGTM

**Comment by Ir1d** [comment]
Landed in 51a7fa8cfe236190bbcbf8471a88630dfd0b3d23.
