### ISSUE TITLE
add 线性同余方程(congruence)

### ISSUE THREAD

**Issue by stevebraveman** [24OI/OI-wiki#267]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

- 英文叫什么？

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by Ir1d** [comment]
landed in https://oi-wiki.org/math/linear-equation/
