### ISSUE TITLE
页面左侧导航栏过长，希望可以自动滚动到当前页面的位置

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#278]
或者折叠起来自动展开?

**Comment by frank-xjh** [comment]
@Ir1d 可不可以在js中用cookie记录下当前滚动条的位置，然后刷新时读取cookie就可以实现这个功能了。

**Comment by Ir1d** [comment]
@frank-xjh 其实这个 issue 指的是左侧目录自动展开到对应页面…… 我想不起来什么时候有的这个需求了= = 感觉其实没有必要。

不过你说的也不错，如果可以恢复到上一次滚动到的位置，的确挺好的。

另外我感觉这个 issue 不如改成，希望右侧 toc 能根据当前位置自动展开……

**Comment by frank-xjh** [comment]
@Ir1d 写了几个js，但是cookie好像有些问题。怀疑是InstantClick造成的。

**Comment by Ir1d** [comment]
不滚了吧，折一折 :new_moon_with_face:
