### ISSUE TITLE
建议cdq分治这一篇回炉重造一下

### ISSUE THREAD

**Issue by Lin1043** [24OI/OI-wiki#294]
对于cdq分治的复杂度分析:一般来说是$T(n)=2T(\frac{n}{2})+f(n)$，然后需要主定理分析（不是什么玄学啊

然后就是log请使用\log 以及不要将$O(n\log^ n)$写成O(n(log n)^2)……

还有可能大概对偏序有什么误解……建议去维基上看看偏序的定义……

**Comment by Ir1d** [comment]
谢谢反馈，也欢迎提交 pr
