### ISSUE TITLE
update 强连通分量

### ISSUE THREAD

**Issue by BalanceUhen** [24OI/OI-wiki#318]
![nvvsr0mjvisy flj5 2 839](https://user-images.githubusercontent.com/21274779/44915090-a4eb0280-ad64-11e8-9f56-26cd29851774.png)

话说这份blog直接给代码不给解释好么?
以及搜索功能可不可以微调一下......搜索第一个字符时总是卡死

**Comment by Ir1d** [comment]
搜索功能计划重构，见 #51 
强连通分量之前是仓促搬运的…… 欢迎一起来完善

**Comment by frank-xjh** [comment]
#402
