### ISSUE TITLE
服务器端渲染数学公式

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#333]
在公式变多之后，可能性能不好的机器加载困难（？）【需要调研】

**Comment by frank-xjh** [comment]
KaTeX???

**Comment by Ir1d** [comment]
计划部署 https://github.com/pkra/mathjax-node-page，正在最后测试

**Comment by greyqz** [comment]
@Ir1d 建议暂时不要 merge，数学公式中没有加 `\text{}` 的汉字在 SVG 渲染下会出现挤在一起的现象。

参考页面：https://new.oi-wiki.org/string/sam/。

**Comment by MingqiHuang** [comment]
啊...这样的话...适当修一些页面吧。
![default](https://user-images.githubusercontent.com/19746684/44950914-dd373180-ae87-11e8-8f8b-3e7eded27742.png)

**Comment by MingqiHuang** [comment]
@greyqz 啊... 这情况也没那么糟。不过加了 `\text{}` 之后有些东西会出锅吧，比如位运算那一页什么的？

**Comment by Ir1d** [comment]
可能是字体问题？我还没仔细研究
其实之前也用过svg 不像现在这样

**Comment by greyqz** [comment]
@MingqiHuang 突然看到图上一个新问题，要用 `\varnothing` 表示空集而不是 `\emptyset`。我在 HOW TO CONTRIBUTE 里面有写到这点。

**Comment by greyqz** [comment]
字距的问题，我电脑上比较明显，有时是挤在一起，有时是大大分离。我觉得是 LaTeX 的锅，肯定要用 `\text{}` 包括。

**Comment by MingqiHuang** [comment]
@greyqz 国外文献一般用 `\emptyset` 比较多吧，但是人教版教材是 `\varnothing`。

`\text{\ttSOMETHING\rm}` 这样可能会出锅吧qwq

**Comment by cjsoft** [comment]
使用MML模式，或者在渲染服务器上安装相应中文字体应该可以解决字体问题，

**Comment by greyqz** [comment]
@MingqiHuang 我倒觉得 `\emptyset` 和 `\phi` 像……不过确实存在这个符号上面的分岐。

p.s. 既然我们做的是**中文 OI Wiki**，还是按照 **中国风** 来书写吧？（中国风 还包括 使用 `\mathbf{N}^*` 而不是 `\mathbb{N}^*`。）

**Comment by MingqiHuang** [comment]
Q∀Q

**Comment by Ir1d** [comment]
@cjsoft > 字体出锅的问题可能是服务端渲染环境没有安装相应字体

confirmed, 我本地跑出来效果这样：
![image](https://user-images.githubusercontent.com/10709657/44953109-ff4da580-aec1-11e8-9340-7a1d6866a1e4.png)

等研究下怎么放到 ci 里

**Comment by MingqiHuang** [comment]
在文档里搜了一下：
> This is the font-family CSS value used for characters that are not in the selected font (e.g., this is where to look for characters not included in the MathJax TeX fonts). IE will stop looking after the first font that exists on the system (even if it doesn’t contain the needed character), so order these carefully.

所以为什么不考虑用衬线字体呢？

另外在 MathJax 中设置字体要用到 `MathJax.Hub` 的相关设置，如：
```js
MathJax.Hub.Config({
  SVG: {
    undefinedFamily: "STIXGeneral, 'Arial Unicode MS', serif"
  }
});
```
所以对应地，我们应该去修改 `mjnodeConfig` 这一项才有效：
> mathjax-node-page exports mjpage which expects four parameters:
> ```js
> mjpage(input, mjpageConfig, mjnodeConfig, callback)
> ```
> Where input is a string with HTML, pageConfig specifies page-wide options, and mjnodeConfig expects mathjax-node configuration options.

摘录自 [Usage](https://github.com/pkra/mathjax-node-page#usage).

而默认的 `mjnodeConfig` 没有设置这一项。

**Comment by Ir1d** [comment]
@MingqiHuang 我重新渲染了一下 https://new.oi-wiki.org/OI-wiki/site/string/sam/#endpos

以及我想问下 endpos 这里是否属于滥用公式字体？按照我的理解这里没有必要用公式字体

**Comment by MingqiHuang** [comment]
@Ir1d 嗯... 这个地方原文就是这样的，我原样保留下来了，如果算滥用字体的话，改掉也是可以的。

**Comment by MingqiHuang** [comment]
@Ir1d 嗯... 这个地方应该不会翻车的。毕竟只是简单的替换。

**Comment by greyqz** [comment]
@Ir1d @MingqiHuang 我倒觉得不必要改。

Italic Latin 的用途就是做变量名，既然 TA 认为这个是变量，就应该保留。如果另一个人认为是常量，就使用 Roman 或 Capitalised Roman。公式应该满足人的需求，如果 TA 真的喜欢莱布尼茨式的画风（雾），也不妨碍。

p.s. 莱布尼茨的画风就比如 微积分里的 $dx$, $dy$ 等。
