### ISSUE TITLE
删除「建议阅读时间」提示

### ISSUE THREAD

**Issue by MingqiHuang** [24OI/OI-wiki#336]
由于每个人的姿势水平和接受能力不同，阅读速度也不同。鉴于之前按每分钟 300 字计算速度过快，而现在按每分钟 80 字计算速度又过慢。建议将「建议阅读时间」提示删除。否则就会出现一篇文章要连续阅读 3 - 4 小时的尴尬的情况。

**Comment by LuoshuiTianyi** [comment]
+1,而且代码也算进去了= =

**Comment by frank-xjh** [comment]
这是大家投票投出来的，比较公正
