### ISSUE TITLE
有关排版的一些建议

### ISSUE THREAD

**Issue by MingqiHuang** [24OI/OI-wiki#373]
我们现有的排版细则要求过于复杂。考虑到我们并没有太多的时间纠结于 Markdown 代码的排版问题（同时也为贡献者带来了不便），可以考虑引入外部 JS 来展现给最终用户良好的阅读体验的方案。

例如 [Han.js](https://css.hanzi.co/) 及其文档 [Han.js Manual](https://css.hanzi.co/manual) 都是相当成熟的解决方案，国内也有应用。

我希望 Wiki 不仅仅在内容上能给人一种良好的感觉，在网页排版上（至少在现有技术条件下）也能给用户以最好的体验，同时也不应该给内容贡献者与审核人员以太大的负担（PR 里面全部都是格式需修正格式需修正）。既减轻了审核的负担，提高了效率，也减轻了贡献者的压力（代价是略降低了页面加载速度）。

这样的话，大概大家只需要注意 LaTeX 的那套语法就好了。

（但是后端看代码还是一团糟啊，这个除了手动修理好像没什么办法解决 XD）

upd(Ir1d):

- [x] remark-lint
- [x] Han.js

**Comment by Ir1d** [comment]
我发现 mkdocs 在用 markdownlint-cli 来排版，不过这个没有 auto-fix 的功能。
关于引入外部 js，我觉得可以考虑一下，之前不知道 Han.js

**Comment by Ir1d** [comment]
要不要大力上 prettier 啊，把翻车的地方手动加个 ignore？

大家觉得如何？

/polls '上 prettier' "不要上 prettier"

**Comment by MingqiHuang** [comment]
1.  Markdown 的设计初衷本身是为了更快地记录下来，是一种轻量化 Mark-up Language（标记语言）。本身并不具有很强的格式性（依赖于 Parser 的实现）。
2.  我们并不是要格式化 Markdown 代码，而是在尽量减小工作量的基础上尽量优化阅读体验，即在未来我们并不要求贡献者严格按照现有的这一套标准书写 Markdown 代码，风格可以自由一点，但是经过处理呈现给读者的页面应该具有优秀的排版（达到接近 LaTeX 的效果）。
3.  现有的技术水平，在用户能力范围内，只能通过浏览器、用户脚本或插件等实现基本的排版。至于中文排版要求中的排版禁则，如禁止顶头点、标点压缩等显然没有实现。这些通过一些手段可以解决。
4.  即使我们自己修排版，严格按照现有的规范，我们还是无法控制浏览器的行为。即我们根本无法避免不符合中文排版习惯的情况出现。这一点在 SAM 那一页有出现过。
5.  我还是希望我们能以内容为主（只要呈现给读者的页面是优秀的，类似 TeX 的哲学，源代码写成什么样我不管，但是出来的文档都是漂亮的文档）。尽量减轻贡献者的负担，同时不要忘记 Markdown 实际上只是一个标记语言，不是使用了 Markdown 就万事大吉。
6.  我并不赞成直接上 lint 工具。正如您所说的，lint 工具与一些插件有冲突。同时我认为对 Markdown 代码进行 lint 是没有意义的。一方面，Markdown 本身就是为了快速记录而生的，本身语法比较松散。我们以后对 PR 进行 review 时，不一定需要读 Markdown 源码，我更推荐审核者能够作为一个读者，对 PR 进行审核【毕竟 Wiki 是写给人看的，同时读者并不（至少是很少）在意页面背后的 Markdown 代码】。这样我们就可以更好地从读者角度出发来评价这个页面了。直接上 lint 工具来解决我们格式的问题未免有些过于粗暴了。

以上皆为个人意见，仅供参考。

**Comment by Ir1d** [comment]
我主张以内容为主，很高兴在这点上似乎终于达成了一致。

遇到格式不规范的地方，能修的修之，没空的话就先丢在那里好了。

为什么现在卡住？因为我们必须要遵守 mkdocs 的格式（来格式化 markdown 文件），不能把一个崩掉的页面部署上去。另一方面，也出于希望能引导 contributor 熟悉我们需要的格式。

> 我们还是无法控制浏览器的行为

这个在 mathjax 服务器渲染上 #333 也遇到了，不同机器上会 fallback 到不同的字体，甚至可能影响文字大小。这有点超出我们需要考虑的范围了XD

我个人比较倾向于把中文排版指南当做是建议而不是标准，不需要特别严格执行。

**Comment by Ir1d** [comment]
另外，对 markdown 文件 lint 并非没有意义，会有助于项目内统一风格 #178 

比如

MD010/no-hard-tabs
MD012/no-multiple-blanks

再比如，中英文之间加空格

这个项目的 goal 并不是 ‘快速记录’，所以我觉得在能统一的地方上不妨使用自动化工具

**Comment by MingqiHuang** [comment]
唔。如果有自动化工具来统一格式当然最好了。我个人可能受 LaTeX 的影响太重了。我个人还是不建议使用特别的 Markdown 语法的。毕竟 Markdown 的 flavor 太多了，彼此不能兼容的地方太多了。我个人倾向于使用 Plain Markdown 或 GFM。我日常使用 Markdown 也只使用 Markdown 的一个很小的子集，复杂的排版任务都丢给 LaTeX 了 XD

我们不妨在 CI 中加入对 Markdown 的 lint check，不过 lint 就不能 merge 进去。

**Comment by Ir1d** [comment]
Landed.
