### ISSUE TITLE
关于赛制的介绍

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#385]
各种营啥的…… 表示没参加过，需要拉一些年轻人写了（

**Comment by P6174** [comment]
有啥赛制啊  
NOI, IOI, ICPC, CF, GCJ，还有哪些？

**Comment by P6174** [comment]
TopCoder 不了解，我不做评论

**Comment by Ir1d** [comment]
@P6174 我理解是各种学科营也可以放进来介绍一下……？

**Comment by P6174** [comment]
学科营……不了解 （溜了
