### ISSUE TITLE
refine images

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#39]
- [x] 比如：[http://oi-wiki.cf/math/gauss](http://oi-wiki.cf/math/gauss) 改成 MathJax

- [plantuml.com](https://plantuml.com/) 用类似工具重画流程图

- [https://github.com/knsv/mermaid](https://github.com/knsv/mermaid)

- 参考人家 e-maxx-eng 是怎么搞的

- LaTeX 画 SVG 不错（学习曲线陡峭，需要很长时间来学习）

- 画图工具：Draw.io、Process On、PlantText、StarUML ref:https://github.com/CyC2018/CS-Notes/issues/314

**Comment by MingqiHuang** [comment]
LaTeX 画 SVG 依赖于 TikZ PGF 等等宏包，可是这些宏包真的难用（至少是需要花不少时间学习）。

**Comment by tiger0132** [comment]
其实ppt+vectormagic画svg也不错(虽然不提倡盗版)

比如下面这个：

![](https://inf.tiger0132.tk/2018/07/19/splay-notes/src.svg)
