### ISSUE TITLE
整理数学部分

### ISSUE THREAD

**Issue by P6174** [24OI/OI-wiki#397]
![Snipaste_2018-09-08_14-36-14.png](http://z4a.net/images/2018/09/08/Snipaste_2018-09-08_14-36-14.png)  
分成几个小版块吧

**Comment by Ir1d** [comment]
嗯 是指折叠起来吗？因为一直没想好怎么折

**Comment by P6174** [comment]
差不多

**Comment by Ir1d** [comment]
via #732
