### ISSUE TITLE
更换搜索工具

### ISSUE THREAD

**Issue by frank-xjh** [24OI/OI-wiki#402]
由于原来的搜索会有迟钝、卡住等种种问题，现准备使用Elasticsearch

**Comment by frank-xjh** [comment]
研究了下elasticsearch，索引比较麻烦，要爬虫，准备使用algolia

**Comment by Ir1d** [comment]
algolia-docsearch 我没找到办法解决 #51 截图里的问题
除非有办法解决，目前 elasticsearch 仍然是首选

**Comment by frank-xjh** [comment]
或许可以用solr???

**Comment by Ir1d** [comment]
之前忘记给索引开 gzip 了…… 现在开了 感觉还可以接受？

**Comment by Ir1d** [comment]
Deployed~
