### ISSUE TITLE
动态规划优化及其他公式大小问题

### ISSUE THREAD

**Issue by BalanceUhen** [24OI/OI-wiki#409]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

![image](https://user-images.githubusercontent.com/21274779/45282202-d86c2080-b50c-11e8-8139-1a33863b52d2.png)
如图，可以看到这几个公式的大小明显不对。
![image](https://user-images.githubusercontent.com/21274779/45282276-0c474600-b50d-11e8-881e-c91a87e46a31.png)
可以看到该页面中有许多公式都出现了这个问题。

- 你是否正在着手修复？

我并不是很会用`Pull Request`，因此只是来汇报一下问题。

- 如何复现？

[网页地址](https://oi-wiki.org/dp/optimization/)
刷新之后情况依然存在。

issue 标题请写为 要汇报的主要内容

**Comment by BalanceUhen** [comment]
![image](https://user-images.githubusercontent.com/21274779/45282664-23d2fe80-b50e-11e8-9ba0-06f423f41990.png)
发现我点击编辑的时候看到的公式是正常的。

**Comment by Ir1d** [comment]
@BalanceUhen 谢谢反馈，这个公式问题是因为我们把渲染过程挪到了服务器上来搞，它就没办法适配屏幕了。
为了解决公式缩放的问题，改了下 css，貌似是改错了 :smile: 
然后我这里直接打开看没有复现，然而手动(ctrl + 滚轮)之后发现的确如此……

至于为什么编辑的时候正确，我猜是因为你装了 github 上显示 mathjax 的插件，它是在浏览器上解析公式，所以不会遇到这个问题。

ref: #410

可以麻烦你看下效果吗？ https://deploy-preview-410--oi-wiki.netlify.com/dp/optimization/#_10 我这里已经正常了（即使手动ctrl滚轮也正常）
