### ISSUE TITLE
是否需要一个 personal access token 来获取 Github API

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#424]
现在除了 Gitment 以外没用 token，好像每小时限制 60 次，然而一个页面会有多次 api 调用，可能访问次数变多体验会不够好？

i.e. 开这个 issue 讨论下真的有人会在一小时之内访问 30+ 页面吗？

ref:  上周统计（虽然可能把爬虫统计进去了，然而还是能说明一些问题吧 :smile: ）
![image](https://user-images.githubusercontent.com/10709657/45377187-6b4fac80-b62c-11e8-99b6-cac861855549.png)

[![](https://api.gh-polls.com/poll/01CQ4M4CA9VNESGFCVRBSA07TT/%E4%BC%9A)](https://api.gh-polls.com/poll/01CQ4M4CA9VNESGFCVRBSA07TT/%E4%BC%9A/vote)
[![](https://api.gh-polls.com/poll/01CQ4M4CA9VNESGFCVRBSA07TT/%E4%B8%8D%E4%BC%9A)](https://api.gh-polls.com/poll/01CQ4M4CA9VNESGFCVRBSA07TT/%E4%B8%8D%E4%BC%9A/vote)

**Comment by Ir1d** [comment]
@Xeonacid 哪个图片挂了？

**Comment by Xeonacid** [comment]
唔窝现在正常了（

**Comment by Ir1d** [comment]
查了下，遇到了点困难，用一个 token 的话是限制一小时 5k 次。
gitment 没有这个问题，是因为它是个 github app，根据授权用户数量会增加 rate-limit

ref: https://developer.github.com/apps/differences-between-apps/

目前我没有什么解决方案 QAQ

或者感觉可以完全抛弃每次调用 Github API，而是单独维护一个 json，然后在 CI deploy 之前把我们需要的信息加进去。
