### ISSUE TITLE
图片如何上传？

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#429]
![QQ20180912192802.png](https://www.z4a.net/images/2018/09/12/QQ20180912192802.png)

怎么做？普通上传是传不进去的。

![QQ20180912193435.png](https://www.z4a.net/images/2018/09/12/QQ20180912193435.png)

**Comment by Ir1d** [comment]
1. 到你的 fork 里面：https://github.com/CBW2007/OI-wiki
2. 去要上传的文件夹：https://github.com/CBW2007/OI-wiki/tree/master/docs/ds/images
3. 上传图片：
![image](https://user-images.githubusercontent.com/10709657/45422731-af41c080-b6c3-11e8-95cd-1c06c78d2adb.png)

【注】：“传到当前文件夹” 的意思是：如果在 docs/misc/index.md 这里写内容，就要传到 docs/misc/images/ 文件夹
