### ISSUE TITLE
add 线性基 (Liner_Base)

### ISSUE THREAD

**Issue by stevebraveman** [24OI/OI-wiki#463]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

- 英文叫什么？

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by Ir1d** [comment]
之前以为这个 issue 的意思是要占个坑……

要添加到目录里的话记得注明一下啊 :smile: 

传送门：https://github.com/24OI/OI-wiki/edit/master/docs/math/basis.md
