### ISSUE TITLE
建议在每一页加上完成进度统计

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#527]
我建议在每一个分类的index.md中都加上这一个分类的完成进度，再在主页中放置每个分类的大统计（未完成/已完成），然后在每次有人更新内容时把完成进度进行修改，就不需要[该issue](https://github.com/24OI/OI-wiki/issues/187)了。

**Comment by Ir1d** [comment]
维护成本比较高（懒
暂时没有这个计划吧
如果有人愿意负责更新这方面的统计也可以联系我
