### ISSUE TITLE
关于自动化初始Gitalk

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#540]
如题。    
目前的新内容提交后的初始化主要靠 @Ir1d  手动。     
打算改成自动化的，但是又怕建重复了。     
***     
目前可以参考的：     
[https://www.colabug.com/1784203.html](https://www.colabug.com/1784203.html)    依靠sitemap实现
[https://developer.github.com/v3/issues/#create-an-issue](https://developer.github.com/v3/issues/#create-an-issue)  Github提交Issues的API       

还有，我在after_deploy里加上了推送百度的脚本，如有需要可以借用。       

***   
希望是merge后提交到GithubPages部署时，就自动建好Issue。      
欢迎有志之士前来造轮子。

**Comment by Ir1d** [comment]
0.0 其实我手动来开 负担也不是很重 :smile: 如果有优雅的自动开 issue 方案，我当然也是滋兹的（
