### ISSUE TITLE
gitalk手机上显示有问题

### ISSUE THREAD

**Issue by open233** [24OI/OI-wiki#572]
试着往下滑，评论框上面的“n条评论”会在页面最顶层，字会跑到顶栏(貌似不是这样叫)上面

**Comment by open233** [comment]
我在我们班的小网站上测试了gitment，gitalk，valine，livere，结果gitment没有配置成功，gitalk出现上述问题，valine在Firefox上显示字体过小，并且输入英文s会触发搜索，livere没有碰到问题。

**Comment by Ir1d** [comment]
感谢反馈 这个其实很早就注意到了，但是一直不知道咋改，而且电脑访问也有类似现象……

> 我在我们班的小网站上测试了gitment，gitalk，valine，livere，结果gitment没有配置成功，gitalk出现上述问题，valine在Firefox上显示字体过小，并且输入英文s会触发搜索，livere没有碰到问题。

gitment 的那个反代最近好像挂了，我们也是因此换到了 gitalk。livere 似乎被墙了。触发搜索的问题在 oi wiki 有遇到吗？还是说别的站点？解决办法可以参考 https://github.com/24OI/OI-wiki/blob/master/static/disqus.html#L17 加一个 `onsubmit="return false;"`

**Comment by open233** [comment]
触发搜索是在我的网站上出现的，valine的问题
