### ISSUE TITLE
建议删除Testlib页面

### ISSUE THREAD

**Issue by StudyingFather** [24OI/OI-wiki#578]
在[spj](https://oi-wiki.org/intro/spj/)里面已经提到了Testlib的详细使用方法，所以把[Testlib页面](https://oi-wiki.org/intro/testlib/)留着似乎没有什么必要了吧。

**Comment by Xeonacid** [comment]
Testlib可以用来写checker, generator, validator, interactor，spj页面只简单介绍了checker
