### ISSUE TITLE
导出 pdf

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#603]
读 https://github.com/e-maxx-eng/e-maxx-eng/issues/320 有感（

列一下我调研的相关工具吧：

https://github.com/jgrassler/mkdocs-pandoc
https://github.com/twardoch/mkdocs-combine
https://github.com/shauser/mkdocs-pdf-export-plugin - 貌似数学公式支持的不好

目前想到几个问题：

1. 折叠起来的部分要展开
2. 图片要处理好，跑了一下发现好像有的 svg 不能导入进来
3. 不同页面之间的内链要处理好

upd:

经过一段时间的尝试，感觉有两种可行方案

1. 魔改了一波 mkdocscombine，然后用合成的 md，再调用 chrome 生成 pdf
2. 搞个 pandoc 的模板，现在 mkdocscombine 的输出按理说可以直接导入 pandoc，然而图片一直提示我 `determine size of graphic in (no BoundingBox)`

**Comment by Ir1d** [comment]
[v0.0rc1.pdf](https://github.com/24OI/OI-wiki/files/2505569/v0.0rc1.pdf)

**Comment by CBW2007** [comment]
文字字体各不相同还可行

![截图](https://www.z4a.net/images/2018/10/23/QQ20181023203917.png)

**Comment by CBW2007** [comment]
我觉得底部的作者信息和协议或许应该留着？

另：wiki崩了？

![](https://www.z4a.net/images/2018/10/23/QQ20181023204309.png)

**Comment by Ir1d** [comment]
@CBW2007 留着那部分的话太乱了…… 字体是因为我生成的时候忘记设置了

截图里 Network Error 我猜是连不上 Github？注意到贡献者那部分也没加载出来，可以 F12 看看

目前我觉得就用  chrome 生成 pdf 吧，尝试 pandoc，感觉改公式成本太高了，根本定位不出来是哪个公式翻车了，暂时先不使用 LaTeX 来生成

**Comment by MingqiHuang** [comment]
公式问题将在以后修改。所有翻车了的公式都会修正（Flag）。不过 MathJax 真的是公式写成什么样都能渲染出来啊（

**Comment by Ir1d** [comment]
图片的问题我解决了 把svg转成png就好了
3和6你看我发的那个里面有遇到吗 我处理了一下

公式感觉修起来工程量很大。。

**Comment by CBW2007** [comment]
@Ir1d 留作者信息不乱啊，除非你像现在这样所有文章放在一起

**Comment by Ir1d** [comment]
用 chrome 导出似乎已经解决了，而且可以做到自动更新

我个人还是倾向于 chrome 一波（×

先看看 latex 造出来的效果以及维护成本如何吧

**Comment by Ir1d** [comment]
上传一个粗糙的版本 
[oi-wiki-18.12.pdf](https://github.com/24OI/OI-wiki/files/2633815/oi-wiki-18.12.pdf)
