### ISSUE TITLE
建议修改关于系统自带 vim 的表述

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#649]
> 但是自带的 Vim 很容易有功能残缺，比如有的就不能与系统剪切板交互 (将会在进阶篇讲解)，各种未开启支持。那么这时候我们就需要手动安装，方法有二。第一步先是卸载 Vim

我理解意思是想要 `sudo apt --only-upgrade install vim` ？

**Comment by Kewth** [comment]
而且也并没有进阶篇

**Comment by LuoshuiTianyi** [comment]
要NOIP了^_v,暂时不敢填坑了,NOIP之后会填上的QAQ

**Comment by Ir1d** [comment]
goto #698
