### ISSUE TITLE
文件操作页面内容显示不全

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#665]
不知道travis是咋回事……
https://oi-wiki.org/basic/file-operation/

然而netlify上面的就是正常的
https://demo.oi-wiki.org/basic/file-operation/

**Comment by abc1763613206** [comment]
可能与这个相关 #666

**Comment by Ir1d** [comment]
好像重新部署之后没有出现这个问题了…… 有点迷

**Comment by abc1763613206** [comment]
玄学问题......先把标签撤了吧
