### ISSUE TITLE
数学筛法部分埃氏筛的代码写成了欧拉筛

### ISSUE THREAD

**Issue by indiewar100** [24OI/OI-wiki#668]
- [v] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
素数筛法部分，埃氏筛的代码写成了欧拉筛，建议重新编写

**Comment by Ir1d** [comment]
谢谢提醒，欢迎 Pull Request
