### ISSUE TITLE
[not a bug, long term] Export PDF with LaTeX

### ISSUE THREAD

**Issue by MingqiHuang** [24OI/OI-wiki#671]
我永远喜欢 LaTeX！

-----------

本 Issue 为一个长期工程，目的是将这个仓库的源码用 LaTeX 写一份，方便导出 PDF。同时 LaTeX 所生成的 PDF 质量也比较高，也能较好地解决直接使用 Markdown 导出 PDF 的排版、内链等问题。

另外 LaTeX 对本仓库使用的 Markdown 插件的资辞有限，应该会使用 boxes 来达到类似的效果，但是很遗憾，不太资辞折叠。

现在存在以下几个问题：
1. ToC 的位置应该在何处？网页形式交互比较灵活，ToC 可以随页面滚动而移动，而 LaTeX 不能做到这一点（或许需要提醒一下善用书签？）。
2. 公式问题。MathJax 与 LaTeX 公式只是类似，并不能互相兼容，这可能会带来比较大的困扰。不过经过一段时间（不会太长）的修正应该可以得到很好的解决。
3. 与本仓库的关系？是作为本仓库的一个分支出现还是作为一个新的仓库？
4. 自动化与模板？感觉可能不太容易，毕竟不兼容的地方太多了，很多修正需要手动完成。

ref: #603 

UPD: `tcolorbox` 宏包可以解决使用的 Markdown 扩展的问题，详见群内的截图。

![yf 1 uhzv5sqqdzc69mt](https://user-images.githubusercontent.com/19746684/47613524-b6822980-dacb-11e8-9e07-85d2c5d978dc.png)

Will be improved soon.

UPD2: 除了排版基线没法调整以外现在插件的一切与 Markdown 效果基本一致了。丢图跑：

![default](https://user-images.githubusercontent.com/19746684/47615710-86e41900-daed-11e8-955d-26769ab275b2.png)

**Comment by Ir1d** [comment]
折叠的话我之前是写个脚本把网页里的都给展开

pdf 里面的目录感觉 chrome 没这功能(https://bugs.chromium.org/p/chromium/issues/detail?id=840455)，latex要是能解决还是最好了。内链其实 chrome 导出的是滋兹的（（

我个人建议搞个脚本来修公式，可能维护更省事（？

不反对开一个新仓库（比如 https://github.com/algmyr/e-maxx-eng-book 这种，当然塞进来的话其实也没啥

感觉其实并不需要自动化，不定期更新也行（？

**Comment by Ir1d** [comment]
mkdocs-combine 的输出

[new.txt](https://github.com/24OI/OI-wiki/files/2522428/new.txt)
[new_withref.txt](https://github.com/24OI/OI-wiki/files/2522429/new_withref.txt)

直接用 latex 来 combine 会不会好一些 :thinking:

**Comment by Ir1d** [comment]
这回加了个 `--keep-levels`，没有改标题
[without.txt](https://github.com/24OI/OI-wiki/files/2522434/without.txt)
[withref.txt](https://github.com/24OI/OI-wiki/files/2522435/withref.txt)

**Comment by abc1763613206** [comment]
#683 和这个一起解决吧？

**Comment by CBW2007** [comment]
> UPD2: 除了排版基线没法调整以外现在插件的一切与 Markdown 效果基本一致了。丢图跑：
> 
> ![default](https://user-images.githubusercontent.com/19746684/47615710-86e41900-daed-11e8-955d-26769ab275b2.png)

我的关注点与别人不一样。。。

提醒一下，还有一种格式叫"example"，效果如图：

![243c5ce4dca2b5e87.png](https://www.z4a.net/images/2018/11/14/243c5ce4dca2b5e87.png)

**Comment by Ir1d** [comment]
[OI-Wiki-Pre-release.pdf](https://github.com/24OI/OI-wiki/files/2612187/OI-Wiki-Pre-release.pdf)

放一个 Pre-release version 出来，感觉效果还可以。不过实时生成 pdf 看来是不可能了 XD

**Comment by Ir1d** [comment]
上传另一个粗糙的版本 
[oi-wiki-18.12.pdf](https://github.com/24OI/OI-wiki/files/2633814/oi-wiki-18.12.pdf)
