### ISSUE TITLE
gitalk 的选项被遮盖

### ISSUE THREAD

**Issue by BalanceUhen** [24OI/OI-wiki#676]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
![image](https://user-images.githubusercontent.com/21274779/47651100-363bf100-dbbd-11e8-8710-8e551bd07909.png)
如图, 可以发现菜单被遮挡住了, 我去gitalk的官网demo测试一下, 发现官方的demo没有这个问题, 就到这里来反馈了

- 你是否正在着手修复？
否

- 如何复现？
登陆gitalk后点击用户名出现下拉菜单即可观察到异常, 已经在多个页面上测试

issue 标题请写为 要汇报的主要内容

**Comment by Ir1d** [comment]
https://github.com/24OI/OI-wiki/commit/f6409b7c0c85aae3b6dc4d55298d5242a9956bab 我猜是这个的问题
