### ISSUE TITLE
打包离线版

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#683]
现在的离线版并不是真的离线……

考虑找一个优美一些的实现方式

参考：https://github.com/ctf-wiki/ctf-wiki/pull/440

**Comment by abc1763613206** [comment]
Electron？

**Comment by MingqiHuang** [comment]
emm... 感觉离线版和 PDF 导出还是要区分一下的。离线版主要是用于屏幕显示，而 PDF 主要是为了印刷，这两者的目标不同，使用不同的解决方案会好一点。举个例子来说，如果直接使用离线版的网页导出 PDF 则会多出印刷中一些不必要元素，同时这样的方案也不适合印刷（CMYK 与 RGB 颜色系统的区别等）。当然如果这个 PDF 主要用于屏幕显示就无所谓了，但是排版要好一点（现在网页的排版还没有达到印刷水平）。

我们应该针对不同的需求作出适当的调整才行。

> This user is currently experiencing mental health issues, which may affect his Code Contribution & Comments in various ways.

**Comment by CBW2007** [comment]
直接发布HTML文档然后再使用软件部署怎么样

**Comment by Ir1d** [comment]
`gh-pages` 分支的就是 html 文档呀…… 这个 issue 想讨论的问题是离线情况如何保证可用，比如调用的js、css放到本地

**Comment by Ir1d** [comment]
目前放了个空的额 service-worker.js，可以考虑之后搞个成熟一些的 pwa，感觉就可以解决离线版的问题了

**Comment by Ir1d** [comment]
相当长的一段时间内没有相关计划，先 close 了
