### ISSUE TITLE
fix: han.css multiple issues

### ISSUE THREAD

**Issue by MingqiHuang** [24OI/OI-wiki#707]
咩 开个 Issue 记录一下 Han.CSS 目前的锅：
1. 文字分散对齐？
~~2. 斜体变成了着重号？~~（Parser 的锅）
2. `<del>` 是否有问题？

还有有什么问题请在下面补充一下。

```cpp
pot.setOwner(MingqiHuang);
```

**Comment by Ir1d** [comment]
个人觉得斜体变成了着重号其实没啥（

**Comment by MingqiHuang** [comment]
emmm... 这个群里之前有人反映了就挂出来吧。

另外，求明确一下使用斜体是 __italic__ or __slant__ 还是 __emphasize__ 的语义。如果是 __emphasize__ 着重号就没啥了，但是如果是前者就不然了，现在这种做法可能会产生歧义。

**Comment by Ir1d** [comment]
我在书中只遇到过表示强调的……

**Comment by MingqiHuang** [comment]
我怕不是对斜体有什么误解？西方是有对斜体做区分的。单纯的斜体用 italic 就行了，有的字体还有 slant。表示强调用 emphasize 加粗。

出锅的地方我猜应该是用了两个下划线表示加粗了？举个例子：

__emphasize__ `__emphasize__`
_italic_ `_italic_`

**Comment by Ir1d** [comment]
closing after discussion: we only support John Gruber's Markdown -- https://daringfireball.net/projects/markdown/
