### ISSUE TITLE
priority_queue部分 内容重复

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#750]
见 #743

**Comment by abc1763613206** [comment]
> 一个STL的一个pb_ds的不算重复吧=-=

@Xeonacid  感觉pb_ds属于STL？个人感觉可以将两部分合起来。

**Comment by Ir1d** [comment]
把 pb_ds 折叠进 stl 底下如何

**Comment by Xeonacid** [comment]
pb_ds不属于STL（

**Comment by Ir1d** [comment]
> pb_ds不属于STL（

@Xeonacid 何以见得

**Comment by Xeonacid** [comment]
@Ir1d emmmm 至少不属于libstdc++基于的SGI STL（
不过窝资瓷把这两个页面合并

**Comment by Planet6174** [comment]
我觉得把评论区拆了就行了 =_=
