### ISSUE TITLE
建议添加洛谷日报专区

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#775]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

洛谷日报专区（毕竟日报里有很多有用的东西），建议主要介绍除算法之外的内容。

- 英文叫什么？

Luogu diary

- 有什么参考资料？

https://www.luogu.org/discuss/show/48491

issue 标题请写为 'add ' + 要添加的内容

**Comment by Ir1d** [comment]
咦，你觉得怎么添加比较好呢？

我们欢迎竞赛相关的内容，只不过由于精力有限，目前写的大多是偏实用一些的知识 :smile:

**Comment by ChungZH** [comment]
开个分区

**Comment by ChungZH** [comment]
不过可能要联系一下洛谷的人，不知道可不可以引用。

**Comment by CBW2007** [comment]
@Ir1d @ChungZH 

> 咦，你觉得怎么添加比较好呢？
> 
> 我们欢迎竞赛相关的内容，只不过由于精力有限，目前写的大多是偏实用一些的知识 😄

通过原作者或wik作者进行转载，并在文章开头对文章源链接&作者进行注明。

> 不过可能要联系一下洛谷的人，不知道可不可以引用。

这个是有必要，不过“洛谷日报”的内容不一定要同原内容一模一样。

**Comment by WZKSDN** [comment]
可以考虑加一个分区，是一些人写的类似洛谷日报的文章（在标准框架之外的），经过遴选之后添加 @Ir1d @ChungZH

**Comment by Ir1d** [comment]
谢谢！我觉得这个提议很有趣，如果“洛谷日报”中出现了质量比较高的文章，我会关注一下
