### ISSUE TITLE
Gitalk问题

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#794]
<https://github.com/24OI/OI-wiki/issues/761#issue-380671179>

<https://github.com/24OI/OI-wiki/issues/603#issuecomment-432230989>

去上面的链接看。

不要再直接丢给我一句“F12看问题”然后直接关issue了！

**Comment by Ir1d** [comment]
:new_moon_with_face: 所以你 f12 看到什么报错了呢？

**Comment by CBW2007** [comment]
@Ir1d 

![qq 20181125110622](https://user-images.githubusercontent.com/42204218/48975030-58347080-f0a2-11e8-94bb-d03a46387d45.png)
![qq 20181125110643](https://user-images.githubusercontent.com/42204218/48975031-58347080-f0a2-11e8-8336-d093cc271a1a.png)
![qq 20181125110656](https://user-images.githubusercontent.com/42204218/48975032-58cd0700-f0a2-11e8-909b-3eba49dbca29.png)
![qq 20181125110705](https://user-images.githubusercontent.com/42204218/48975033-58cd0700-f0a2-11e8-8cdb-614b812713ce.png)

话说这也是很玄学了，就我的电脑有问题，其他的都可以

**Comment by Ir1d** [comment]
用的什么浏览器，会不会是什么插件的问题……

**Comment by CBW2007** [comment]
Google Chrome 69.0.3497.81（正式版本） （32 位）

无插件

**Comment by CBW2007** [comment]
垃圾hosts毁我青春

![qq 20181125125412](https://user-images.githubusercontent.com/42204218/48975665-3e4e5a00-f0b1-11e8-9264-e2ebebfe5332.png)

注释掉下面这一段后......好了？！

疑似网上的Google hosts IP不对

**Comment by Ir1d** [comment]
我也改了 hosts 然而并不能复现

**Comment by CBW2007** [comment]
改完后长这样：

![qq 20181125133832](https://user-images.githubusercontent.com/42204218/48975931-7f496d00-f0b7-11e8-88e2-22fd597f32d3.png)
![qq 20181125133854](https://user-images.githubusercontent.com/42204218/48975932-7fe20380-f0b7-11e8-8fdd-4409a634a186.png)

**Comment by Ir1d** [comment]
@CBW2007 弄好了就行～
没有印象 GoogleHosts 加过这几个条目，建议去他们的群里问问吧，我也不是很清楚怎么回事。总之 Gitalk 看起来没问题……
