### ISSUE TITLE
add 最长不下降子序列

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#83]
https://github.com/Ir1d/gitment/issues/1#issuecomment-412385090

**Comment by CBW2007** [comment]
@Ir1d 等有时间时，我来写一下吧

**Comment by CBW2007** [comment]
突然发现n log n算法不会写(汗

**Comment by CBW2007** [comment]
> 
> 
> [Ir1d/gitment#1 (comment)](https://github.com/Ir1d/gitment/issues/1#issuecomment-412385090)

**Comment by CBW2007** [comment]
施工完毕 #505

**Comment by CBW2007** [comment]
@Ir1d PR可以关了不

**Comment by Ir1d** [comment]
辛苦啦
