### ISSUE TITLE
本地搭建失败？

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#833]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

（第一个输入的命令是mkdocs build，没有截图出来）

![qq 20181205200038](https://user-images.githubusercontent.com/42204218/49512307-84cd6100-f8c8-11e8-877a-b020ece4ca8d.png)

本地搭建失败？

- 你是否正在着手修复？

NO

- 如何复现？

Windows Python3 Mkdocs v1.0.4，以及当前仓库中的最新代码。

issue 标题请写为 要汇报的主要内容

**Comment by Ir1d** [comment]
`pip install -U -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/`

**Comment by CBW2007** [comment]
哦
