### ISSUE TITLE
SAM内容有误

### ISSUE THREAD

**Issue by partychicken** [24OI/OI-wiki#849]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
> **引理 3：**考虑一个 $endpos$ 等价类。将类中的所有子串按长度非递增的顺序排序。即每个子串都会比它前一个子串短，与此同时每个子串也是它前一个子串的一个后缀。换句话说，同一等价类中的所有子串均互为后缀，且子串的长度恰好覆盖整个区间 $[x,,y]$。

https://github.com/24OI/OI-wiki/blob/master/docs/string/sam.md#L93
互为后缀表达有误，原因显然。
- 你是否正在着手修复？
否

**Comment by partychicken** [comment]
> 谢谢！欢迎开一个 pull request

目前想不到很恰当的修改方式。我查阅了一下英文译本，翻译的也不大对劲。至于俄语原版，我看不懂。。。

**Comment by Ir1d** [comment]
Google 翻译出来是一样的…… 我想想怎么改，感觉干脆删掉……？

![image](https://user-images.githubusercontent.com/10709657/49870091-4e09c480-fe4d-11e8-8c18-aae66c0596cd.png)
