### ISSUE TITLE
ADD 虚拟机

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#866]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

虚拟机的相关内容，预计使用VMware Workstation 15 Pro演示。

- 英文叫什么？

vm应该就够了

- 有什么参考资料？

[洛谷日报#64[ztz11]真正的全真虚拟机：VmWare Workstation](https://www.luogu.org/blog/ztz11/zhen-zheng-di-quan-zhen-xu-ni-ji-vmware-workstation)

issue 标题请写为 'add ' + 要添加的内容

**Comment by MingqiHuang** [comment]
Would you please use Virtual Box, instead? VMware is not open-source and it cost too much for students.Your article should be legal, not only suitable for Chinese users XD.

**Comment by Ir1d** [comment]
@MingqiHuang suitable for Chinese users 是什么鬼…… 如果是想说不要宣传盗版资源那的确（

**Comment by MingqiHuang** [comment]
其实说实话现在 VM 这个虚拟机已经非常傻瓜化了，个人认为没必要搞这样的一个页面。有需要的人自然会用这种软件吧（我平时需要用虚拟机的环境也就是开 Windows 的虚拟机打个游戏之类的

个人意见，仅供参考。

**Comment by Xeonacid** [comment]
> Your article should be legal
那篇文章里并没有illegal内容 lol

**Comment by CBW2007** [comment]
讲到这我都想弃坑了QwQ，
干脆算了吧，反正我最近有课，没来得及写多少(〃'▽'〃)
