### ISSUE TITLE
我的贡献呢？

### ISSUE THREAD

**Issue by CBW2007** [24OI/OI-wiki#894]
![qq 20190111203100](https://user-images.githubusercontent.com/42204218/51033913-e4154400-15df-11e9-8217-1f0e313dee4f.png)

![qq 20190111203121](https://user-images.githubusercontent.com/42204218/51033914-e4adda80-15df-11e9-9b41-c3d8de69d1e3.png)

我的贡献在哪里？我记得我还是第一个改这个页面的来着？！

**Comment by Ir1d** [comment]
@CBW2007 十分抱歉。因为这里把链接改了 https://github.com/24OI/OI-wiki/commit/7de0d80bfac3c6556da8349091ece32320ff82ad 所以 Github 没能识别出来。过几天会换一种方式来统计，争取避免这种问题。（#480）
如果还发现类似的问题也欢迎再提出来 :heart:
