### ISSUE TITLE
工作记录

### ISSUE THREAD

**Issue by Ir1d** [24OI/OI-wiki#9]
Hi, all

大家有时间的时候可以 edit / reply 一下这个 issue，记录一下 正在填 / 打算填 的内容

cc: @24OI/wiki 

----

**请不要引入会导致 CI fail 掉的 commit**

**Comment by MingqiHuang** [comment]
现任 LOJ 题库维护组成员。
想填后缀自动机。这几天正在学后缀自动机，在翻译几篇文。
[a](http://akshay.jaggi.co/blog/suffix-automata/)
[b](https://e-maxx.ru/algo/suffix_automata)
预计需要 3 天的样子。

**Comment by Xeonacid** [comment]
@MingqiHuang 请确认该博客允许转载/原作者同意+授权协议兼容

**Comment by MingqiHuang** [comment]
@Xeonacid 这两个博客都已经多年没有更新了。没什么办法能与原作者获得联系。

**Comment by MingqiHuang** [comment]
已经确认原文为 Public Domain（作者建议加个链接），英文翻译为 CC BY-SA.

**Comment by Mosa-Linking** [comment]
想填树形dp......不过因为开学了可能会稍微等几天......

**Comment by Ir1d** [comment]
@hsfzLZH1 @cutekibry 麻烦二位给每个内容开个新 issue 吧，感觉用 [Github Project](https://github.com/24OI/OI-wiki/projects/1) 管理更合理一些，二位开新 issue 之后，我给加到看板里面
