### ISSUE TITLE
站点的SEO优化有点问题

### ISSUE THREAD

**Issue by abc1763613206** [24OI/OI-wiki#904]
```
<meta name="description" content="OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛">
```

所有生成的页面都是这个描述，没有实际内容，也没有关键词。     
看样子不利于百度抓取啊，所有抓到的都是同一个描述，也不利于搜索。      

目前个人找到的方案：     

Github上有个魔改过的主题[ahmadawais/mkdocs-material-custom](https://github.com/ahmadawais/mkdocs-material-custom/blob/a557401c53520325bc5c62f894a94e5a77796444/base.html)中加入了一行生成描述的，但不知道是否有效。

```
{% if page_description %}
        <meta name="description" content="{{ page_description }}">
{% endif %}
```

另外关键词的话建议引入分词，和 #51 搜索一起解决，这就有点难受😖

**Comment by Ir1d** [comment]
meta keyword 听说没用啊（

**Comment by Ir1d** [comment]
@abc1763613206

**Comment by abc1763613206** [comment]
> 好像可以…… 主要是不知道这东西如果无脑用文章前100字的话，有咩有效果……
> 
> 因为我听说 description 并不用来算权重啥的……？



主要是便于搜索啊

> @abc1763613206 一句话简介或者文章前 40 个字？

个人感觉要么自己写介绍，没有的话就自己抓取

参照cnblogs

**Comment by Ir1d** [comment]
https://squidfunk.github.io/mkdocs-material/extensions/metadata/#page-description

好像滋兹写在 md 文件首部 :thinking:

**Comment by abc1763613206** [comment]
跑一个bot脚本批量加？

**Comment by Ir1d** [comment]
@abc1763613206 🤔感觉可以

**Comment by abc1763613206** [comment]
等放假折腾下

**Comment by Ir1d** [comment]
@abc1763613206 👍

**Comment by Himself65** [comment]
个人感觉不需要脚本重新生成docs，根据已有的内容完全可以自动生成

**Comment by Himself65** [comment]
fix on https://github.com/Ir1d/mkdocs-material/pull/7

**Comment by Himself65** [comment]
> 跑一个bot脚本批量加？

个人想了几天，觉得有几种方案

1. 直接暴力修改文件，添加meta信息

2. 修改主题html内容，用预处理语言判断是否有meta-description

3. 该项目添加预处理文件，根据是否有meta-description来动态返回数据

**Comment by abc1763613206** [comment]
感谢！@Himself65
