### ISSUE TITLE
可持久化平衡树练手题有误

### ISSUE THREAD

**Issue by hsfzLZH1** [24OI/OI-wiki#914]
https://oi-wiki.org/ds/persistent-balanced/

该页面最下面的练手题中，第二题 T-shirt 只是 FHQ-Treap 的题，并未用到可持久化。建议把此题作为 Treap 的练习题，而添加一道 [P5055 【模板】可持久化文艺平衡树](https://www.luogu.org/problemnew/show/P5055)

**Comment by MingqiHuang** [comment]
#926 had fixed it, closing.
