### ISSUE TITLE
fix(images): 部分示意图过于模糊

### ISSUE THREAD

**Issue by Enter-tainer** [24OI/OI-wiki#976]
部分页面的图过于糊（有明显锯齿），或在美学意义上有点令人难以接受。以下是列举
- [x] 最小生成树 #977 
![mst](https://oi-wiki.org/graph/images/mst1.svg)
- [x] 双联通分量 #977 
![bcc](https://oi-wiki.org/graph/images/bcc-1.svg)
- [x] 割点和桥（鼠绘的叉号）#990
![](https://oi-wiki.org/graph/images/bridge3.png)
- [x] 拆点（鼠绘的箭头）#990
![](https://oi-wiki.org/graph/flow/images/node2.png)
- [x] 最大流（luogu 水印）#990
![](https://oi-wiki.org/graph/flow/images/flow1.png)
- [x] 树状数组（过于飘忽的文字位置）
![](https://oi-wiki.org/ds/images/bit1.png)
- [ ] 虚树（纯鼠绘，但是意外地可爱）
![](https://oi-wiki.org/ds/images/vtree1.png)
- [x] 可持久化线段树（此文同时还有排版问题）
![](https://oi-wiki.org/ds/images/persistent-seg.png)

以及更多，我只 review 了数据结构和图论两部分，更多的还有待发现。
- 你是否正在着手修复？
是的，我准备用`tikz`画一部分，但我自己显然是弄不完所有的图的。

**Comment by Enter-tainer** [comment]
我先认领一下`最小生成树`的图

**Comment by Planet6174** [comment]
@Enter-tainer 
强推 Visio
效果如下
![mst.3.png](https://i.loli.net/2019/02/27/5c762bbdeb2a2.png)

**Comment by Enter-tainer** [comment]
妙哇，用 Visio 画的图也挺漂亮的

**Comment by Planet6174** [comment]
虚树的画图感觉海星，至少不丑  
~~那我就不修了哈~~
